export enum Configuration {
  PORT = 'PORT',
  RINKEBY = 'RINKEBY',
  MAINNET = 'MAINNET',
  ROPSTEN = 'ROPSTEN',

  MAIL_HOST = 'MAIL_HOST',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
  MAIL_FROM = 'MAIL_FROM',

  MAIL_TRANSPORT = 'MAIL_TRANSPORT',

  URL_CONFIRMATION = 'URL_CONFIRMATION',

  URL_API_CRYPTO_EXCHANGE = 'URL_API_CRYPTO_EXCHANGE',

  URL_API_USD_EXCHANGE = 'URL_API_USD_EXCHANGE',
  KEY_API_USD_EXCHANGE = 'KEY_API_USD_EXCHANGE',

  URL_API_TWILIO = 'URL_API_TWILIO',
  ACCOUNT_API_TWILIO_SID = 'ACCOUNT_API_TWILIO_SID',
  KEY_API_TWILIO_TOKEN = 'KEY_API_TWILIO_TOKEN',
  PHONE_SERVER_API_TWILIO = 'PHONE_SERVER_API_TWILIO',
}